### ISSUE TITLE
Table: Blocks

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#1]
## Description
Let's create a Blocks table using ```chainwalkers.prod.near_blocks``` as the source data table, with a deduped staging table upstream of our core blocks table.

## TODO
- [ ] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build deduped table model
- [ ] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request
