### ISSUE TITLE
Metrics: Number of Transactions

### ISSUE THREAD

**Issue by chuxinh** [MetricsDAO/near_dbt#10]
## Description
A table tracking the number of total transactions per day 

## TODO
- [x]  Design the schema for this table
- [x]  Get confirmation on schema
- [x]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request

**Comment by 0xissui** [comment]
Proposed Schema

- [ ] Date (day)
- [ ] Number of transactions (integer)

**Comment by forgxyz** [comment]
I agree with this schema
