### ISSUE TITLE
Metrics: Daily Gas Used and Gas price

### ISSUE THREAD

**Issue by chuxinh** [MetricsDAO/near_dbt#11]
## Description
A table tracking the daily gas usage and gas price

## TODO
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request

**Comment by 0xissui** [comment]
Propsed Schema

- [ ] Date (day)
- [ ] Total Gas Used
- [ ] Average Gas Price
