### ISSUE TITLE
Metrics: New Wallets Created

### ISSUE THREAD

**Issue by chuxinh** [MetricsDAO/near_dbt#12]
## Description
A table tracking the number of new wallets created daily, weekly, monthly

## TODO
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request
