### ISSUE TITLE
Metrics: New Contracts Deployed

### ISSUE THREAD

**Issue by chuxinh** [MetricsDAO/near_dbt#13]
## Description
A table tracking the number of new contracts deployed daily, weekly, monthly

## TODO
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request
- [ ] Dependent on `action` table
