### ISSUE TITLE
Metrics: Active Contracts

### ISSUE THREAD

**Issue by chuxinh** [MetricsDAO/near_dbt#14]
## Description
A table tracking the number of active contracts deployed 

## TODO
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request
- [ ] Dependent on `action` table

**Comment by sedaghatfar** [comment]
Proposed Schema

-  Date (day)
- Active contracts deployed (sum of active wallets for the day)
- Active contracts deployed L7  (sum of Active contracts deployed past 7 days)
- Active contracts deployed  L30(sum of Active contracts deployed past 30 days)

**Comment by 0xissui** [comment]
> Proposed Schema
> 
> * Date (day)
> * Active contracts deployed (sum of active wallets for the day)
> * Active contracts deployed L7  (sum of Active contracts deployed past 7 days)
> * Active contracts deployed  L30(sum of Active contracts deployed past 30 days)

Sorry just seeing this, feel free to start working !

**Comment by sedaghatfar** [comment]
Proposed Schema based on issue found #82

Date (day)
Daily Active contracts events (count of distinct active contracts events for that day)
Weekly Active contracts events  (count of distinct active contracts events for the week)
Monthly Active contracts events ((count of distinct active contracts events for the month)

**Comment by sedaghatfar** [comment]
Snowflake tested code and based off [daily_active_contracts_count.py](https://github.com/near/near-analytics/blob/main/aggregations/db_tables/daily_active_contracts_count.py)
to count distinct tx_receiver's with a  'FUNCTION_CALL' action

```
WITH txn as (
    SELECT 
          t.block_timestamp::date as date
        , t.tx_receiver
    FROM NEAR_DEV.SILVER.TRANSACTIONS t 
    JOIN NEAR_DEV.SILVER.ACTIONS_EVENTS_FUNCTION_CALL aefc ON aefc.tx_hash = t.tx_hash
), daily as (
SELECT
    txn.date
    , COUNT(distinct tx_receiver) as daily_active_contracts
FROM txn
GROUP BY 1
    ), 
weekly as (
    SELECT
        date_trunc('week' , txn.date)::date as week
        , COUNT(distinct tx_receiver) as weekly_active_contracts
FROM txn
GROUP BY 1
    ),
monthly as (
    SELECT
        date_trunc('month' , txn.date)::date as month
        , COUNT(distinct tx_receiver) as montlhy_active_contracts
FROM txn
GROUP BY 1
    )
SELECT
    daily.*
    ,weekly_active_contracts
    ,montlhy_active_contracts
FROM daily
LEFT JOIN weekly  ON weekly.week   = date_trunc('week'  , daily.date)::date
LEFT JOIN monthly ON monthly.month = date_trunc('month' , daily.date)::date
ORDER BY 1
    ```

**Comment by 0xissui** [comment]
Results look good! Go ahead and open a PR for this, and make sure to maintain our dbt styling (check other tables, we use VS code dbt formatter https://github.com/henriblancke/dbt-formatter

**Comment by sedaghatfar** [comment]
Thank you! https://github.com/MetricsDAO/near_dbt/pull/83
