### ISSUE TITLE
Table: Transactions

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#2]
## Description

Let's create a Blocks table using ```chainwalkers.prod.near_txs``` as the source data table, with a deduped staging table upstream of our core txs table.

## TODO

- [x] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build deduped table model
- [x] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request

**Comment by ndhung1104** [comment]
Proposed Schema:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Hp/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Hp/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



BLOCK_ID | BLOCK_TIMESTAMP | TX | TX_HASH | TX_ACTIONS | TX_OUTCOME | TX_RECEIPT | TX_RECEIVER | TX_SIGNER
-- | -- | -- | -- | -- | -- | -- | -- | --
47041604 | 2021-09-05 19:57:17.657 | {       "actions": [         {           "FunctionCall":   {             "args":   "eyJ0YXNrX29yZGluYWwiOjEsImFwcHJvdmUiOnRydWUsInJlamVjdGlvbl9yZWFzb24iOiIifQ==",             "deposit":   "0",             "gas":   80000000000000,             "method_name":   "submit_review"           }         }       ],       "hash":   "8Fyb5XEakxKtYxvrFZT3hpnUPDvEJDKtaPDWeaMX4pac",       "nonce": 47027523000260,       "outcome": {         "block_hash":   "J4BpiyqqZ1RZW3ojVLjQKaqfxCYb5Nq3XRYd66QSnnbK",         "id":   "8Fyb5XEakxKtYxvrFZT3hpnUPDvEJDKtaPDWeaMX4pac",         "outcome": {           "executor_id":   "verver.near",           "gas_burnt":   2428073043512,           "logs": [],           "metadata": {             "gas_profile":   null,             "version": 1           },           "receipt_ids":   [               "Dd79rvdjRDR8wDPhn4ixvzB6NWhVEbTJyiLMhCAoGyxV"           ],           "status": {             "SuccessReceiptId":   "Dd79rvdjRDR8wDPhn4ixvzB6NWhVEbTJyiLMhCAoGyxV"           },           "tokens_burnt":   "242807304351200000000"         },         "proof": [           {             "direction":   "Right",             "hash":   "5tQKptXsxKPauS86rjUkSR3rBCMnX5gPw1Rkhp5m5n5i"           },           {             "direction":   "Right",             "hash":   "4CW5uYxxB4pqKTPp11yL3Jetx3G5aadc2kmuxRFeDUSJ"           },           {             "direction":   "Right",             "hash":   "CAjCLc6a8wgBdS4unpw8CLbvzw92juajbvuQT2LxUABR"           },           {             "direction":   "Right",             "hash":   "CjF6XLhFM1jwinPUbyuNM6bnQ4uCpisTBdgZFrQK3toE"           }         ]       },       "public_key":   "ed25519:A5a6krGvyaifCb9AK9sHgh79bZV9t8C585E1kyuZwY9j",       "receipt": [         {           "block_hash":   "8Fy45gpgodpZqet22RV7ScAPc7ZxxQYof3DtuGFSbGfr",           "id":   "Dd79rvdjRDR8wDPhn4ixvzB6NWhVEbTJyiLMhCAoGyxV",           "outcome": {             "executor_id":   "app.nearcrowd.near",             "gas_burnt":   6066812197193,             "logs": [],             "metadata": {               "gas_profile":   null,               "version":   1             },             "receipt_ids":   [                 "in8fkCq1nwcEy2QyreshJLjaxGkEawdYQe4KJATqLjr"             ],             "status": {               "SuccessValue":   ""             },             "tokens_burnt":   "606681219719300000000"           },           "proof": [             {               "direction":   "Left",               "hash":   "DturwddBVt6L28m9c5AzCS3iw9kV49ktZLHoZVZuGcXm"             },             {               "direction":   "Left",               "hash":   "6ZBv98NuZsro1CLRAsCyCyChTYJyhTASx8CTSo8P2Uum"             },             {               "direction":   "Right",               "hash":   "AMe2J1XcTZif4fnTjCmj4cwW87WpyrSgPse4u4ugnK5W"             },             {               "direction":   "Right",               "hash":   "5ThPhRwZ5EreyX5uqVgo1yM37jAwye3yxdoHRMDNfdqL"             }           ]         },         {           "block_hash":   "7LBCzDNzVKDbJTdBcFvXjzUAuKTr2dfuk6inbve6Qg3J",           "id":   "in8fkCq1nwcEy2QyreshJLjaxGkEawdYQe4KJATqLjr",           "outcome": {             "executor_id":   "verver.near",             "gas_burnt":   223182562500,             "logs": [],             "metadata": {               "gas_profile":   null,               "version":   1             },             "receipt_ids":   [],             "status": {               "SuccessValue":   ""             },             "tokens_burnt":   "0"           },           "proof": [             {               "direction":   "Right",               "hash":   "35ZM9tksD32cAkrMDYTgkM1MaGYZFy3wfhkRcEWZW1qm"             },             {               "direction":   "Left",               "hash":   "4YRX8Xzsdz92J8orhxMWfrFDHw1KA9NJFYcwFL2jxo39"             },             {               "direction":   "Right",               "hash":   "Ac1spSA9bTkkUVpR8mZ9gTRM9UMkViQoQ3mfaeTquekN"             },             {               "direction":   "Left",               "hash":   "GKMWuNg4uQzCaDa9ymhjRN3gVvdcrEQXLRsL4yQxx3bG"             }           ]         }       ],       "receiver_id":   "app.nearcrowd.near",       "signature":   "ed25519:xAhFLsMWfTk2YbTk2uGngSis8zRBeLoQZAQm6DXsMLTiPrtBDVxrUAunDyPLun6RvkTeU4cBwx29qf7xso95Cxf",       "signer_id":   "verver.near"     } | 8Fyb5XEakxKtYxvrFZT3hpnUPDvEJDKtaPDWeaMX4pac | [       {         "FunctionCall": {           "args":   "eyJ0YXNrX29yZGluYWwiOjEsImFwcHJvdmUiOnRydWUsInJlamVjdGlvbl9yZWFzb24iOiIifQ==",           "deposit":   "0",           "gas":   80000000000000,           "method_name":   "submit_review"         }       }     ] | {       "block_hash":   "J4BpiyqqZ1RZW3ojVLjQKaqfxCYb5Nq3XRYd66QSnnbK",       "id":   "8Fyb5XEakxKtYxvrFZT3hpnUPDvEJDKtaPDWeaMX4pac",       "outcome": {         "executor_id":   "verver.near",         "gas_burnt":   2428073043512,         "logs": [],         "metadata": {           "gas_profile":   null,           "version": 1         },         "receipt_ids": [           "Dd79rvdjRDR8wDPhn4ixvzB6NWhVEbTJyiLMhCAoGyxV"         ],         "status": {           "SuccessReceiptId": "Dd79rvdjRDR8wDPhn4ixvzB6NWhVEbTJyiLMhCAoGyxV"         },         "tokens_burnt":   "242807304351200000000"       },       "proof": [         {           "direction":   "Right",           "hash":   "5tQKptXsxKPauS86rjUkSR3rBCMnX5gPw1Rkhp5m5n5i"         },         {           "direction":   "Right",           "hash":   "4CW5uYxxB4pqKTPp11yL3Jetx3G5aadc2kmuxRFeDUSJ"         },         {           "direction":   "Right",           "hash":   "CAjCLc6a8wgBdS4unpw8CLbvzw92juajbvuQT2LxUABR"         },         {           "direction":   "Right",           "hash":   "CjF6XLhFM1jwinPUbyuNM6bnQ4uCpisTBdgZFrQK3toE"         }       ]     } | [       {         "block_hash":   "8Fy45gpgodpZqet22RV7ScAPc7ZxxQYof3DtuGFSbGfr",         "id": "Dd79rvdjRDR8wDPhn4ixvzB6NWhVEbTJyiLMhCAoGyxV",         "outcome": {           "executor_id":   "app.nearcrowd.near",           "gas_burnt":   6066812197193,           "logs": [],           "metadata": {             "gas_profile":   null,             "version": 1           },           "receipt_ids":   [               "in8fkCq1nwcEy2QyreshJLjaxGkEawdYQe4KJATqLjr"           ],           "status": {             "SuccessValue":   ""           },           "tokens_burnt":   "606681219719300000000"         },         "proof": [           {             "direction":   "Left",             "hash":   "DturwddBVt6L28m9c5AzCS3iw9kV49ktZLHoZVZuGcXm"           },           {             "direction":   "Left",             "hash":   "6ZBv98NuZsro1CLRAsCyCyChTYJyhTASx8CTSo8P2Uum"           },           {             "direction":   "Right",             "hash":   "AMe2J1XcTZif4fnTjCmj4cwW87WpyrSgPse4u4ugnK5W"           },           {             "direction":   "Right",             "hash":   "5ThPhRwZ5EreyX5uqVgo1yM37jAwye3yxdoHRMDNfdqL"           }         ]       },       {         "block_hash":   "7LBCzDNzVKDbJTdBcFvXjzUAuKTr2dfuk6inbve6Qg3J",         "id":   "in8fkCq1nwcEy2QyreshJLjaxGkEawdYQe4KJATqLjr",         "outcome": {           "executor_id":   "verver.near",           "gas_burnt":   223182562500,           "logs": [],           "metadata": {             "gas_profile":   null,             "version": 1           },           "receipt_ids":   [],           "status": {             "SuccessValue":   ""           },           "tokens_burnt":   "0"         },         "proof": [           {             "direction":   "Right",             "hash":   "35ZM9tksD32cAkrMDYTgkM1MaGYZFy3wfhkRcEWZW1qm"           },           {             "direction":   "Left",             "hash":   "4YRX8Xzsdz92J8orhxMWfrFDHw1KA9NJFYcwFL2jxo39"           },           {             "direction":   "Right",             "hash":   "Ac1spSA9bTkkUVpR8mZ9gTRM9UMkViQoQ3mfaeTquekN"           },           {             "direction":   "Left",             "hash":   "GKMWuNg4uQzCaDa9ymhjRN3gVvdcrEQXLRsL4yQxx3bG"           }         ]       }     ] | app.nearcrowd.near | verver.near



</body>

</html>

**Comment by forgxyz** [comment]
I think the tx_actions column is not necessary as actions will get its own table

**Comment by ndhung1104** [comment]
I removed the tx_actions and built the table under near.dev.transactions. The source code can be found under the transactions branch. I will do a pull request later if there is no other comment. 


15:06:39 | Concurrency: 4 threads (target='dev')
15:06:39 |
15:06:39 | 1 of 1 START incremental model DEV.transactions...................... [RUN]
15:06:50 | 1 of 1 OK created incremental model DEV.transactions................. [SUCCESS 1 in 10.48s]
15:06:50 |
15:06:50 | Finished running 1 incremental model in 16.57s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
