### ISSUE TITLE
Table: Transfers

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#3]
## Description
Let's create a Transfers table with direct asset transfers between parties.  
This table is downstream of the core Transactions table we will build.

## TODO

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [x] Schema build review
- [x] Submit Pull Request

Note: this is downstream of stg_txs

**Comment by chuxinh** [comment]
Is the `transfer` the same as what `deposit` means in the near block explorer? 
![image](https://user-images.githubusercontent.com/30974572/154684937-02be3122-f3d7-4395-954c-ce78c79c0242.png)
ie a combination of transfer actions and deposits on function call actions

**Comment by forgxyz** [comment]
The structure of the action `Transfer` is:
```
{
  "deposit": "4570719915088988000000000000"
}
```

There is no denom information, so that's probably in `FunctionCall`. However, there are instances of `Transfer` being the only action_event. So, the long and short of it is I don't really know...  

I think the intent of this table is p2p transfers, so we need to figure out how to isolate those from contract calls.

**Comment by antonyip** [comment]
> The structure of the action `Transfer` is:
> 
> ```
> {
>   "deposit": "4570719915088988000000000000"
> }
> ```
> 
> There is no denom information, so that's probably in `FunctionCall`. However, there are instances of `Transfer` being the only action_event. So, the long and short of it is I don't really know...
> 
> I think the intent of this table is p2p transfers, so we need to figure out how to isolate those from contract calls.

This is NEAR blockchain, there will only be NEARcoin transfers. You're thinking in terms of ERC20 which is actually a "FunctionCall" of a SmartContract. Not sure which table you're trying to build tho..

**Comment by mattromano** [comment]
### Proposed Transaction Schema

So after looking through a few txs and the block explorer I think I have an idea of transfers and what makes sense to include. 

| tx_hash | block_timestamp | signer_id | receiver_id | deposit_value | reciept_data
| --- | --- | --- | --- | --- | --- |
| ESesVe7CQgSwN2VQVKDj2ycKLy91bpyk9v2itx7wKJ11 | 2021-10-20 01:31:05.868 | ndovanlanh758.near | ndothitu652.near | 10000000000000000000 | [{ "block_hash": "9veCaMfdN25BpYwwvXQSMmeVt2FjdBbSMGhLyjs2z1]... |

Another option for the above is potentially changing signed and receiver to to_address & from_address. Not sure if we want to standardize across blockchains or follow the nomenclature of the blockchain we're working in.  My thought was that we probably want to match what is displayed in the block explorer. I guess we can also just include this info in the yaml file.

Would also filter this table to only ```Transfer``` actions. I looked through a couple of the ```FunctionCall``` actions but it looks like all of them are to app. address types which I assume are smart contracts. So if we want to keep this p2p I think just limiting to transfers should do the trick. I did see a transfers to/from ```app.nearcrowd.near``` but maybe that's like a protocol level thing? I think I will filter out transfers that are to or from ```app.nearcrowd.near```

Pretty new to the Near data and so if there's anything I should add or remove let me know. 

CC: @chuxinh @forgxyz  @antonyip

**Comment by antonyip** [comment]
![image](https://user-images.githubusercontent.com/9086733/157986323-dfe19a20-8f38-4d45-b521-debe1d520c89.png)
Forgive me for my questions ( I don't know near's data structure off the back of my hand. + I don't know if they are easy to extract). I just figured that maybe people would cross reference to the explorer and thus expect these fields to be there. (Also these fields will be good to generate metrics later on)

Do we want to add these columns?
- status
- transaction fee
- gas used
- attached gas

I'm just also wondering why you would want to filter `app.nearcroud.near`? My feeling is to let the user do the filtering themselves if they wish to.

**Comment by forgxyz** [comment]
I agree we should add those four columns, especially status so the end user can filter by Succeeded and Failed, as needed. It's my thought, as well, that we should include all transfers and not filter out `app.nearcloud.near`.

**Comment by mattromano** [comment]
Awesome, thanks for the feedback guys! 

I will incorporate those additional columns as well as keeping the ```app.nearcloud.near``` in the transfers table. My only reason for the filtering was that I didn't think it was an actual p2p transfer but I make sense to just let the user filter on there own. And it is still a transfer based on their own actions so I think keeping it in there makes the most sense.

I'll create the PR and start working on building out the schema. Let me know if there's any other questions or things to add.

**Comment by forgxyz** [comment]
Please use `txn_hash` for that column.  
We should also discuss `signer_id` and `receiver_id` in the chat as the current `transactions` table uses `tx_receiver` and `tx_signer`. The `receipts` table will also include reference to a NEAR address, so all tables should use a schema common to NEAR. Looks like their explorer currently uses the format: `_id`.

**Comment by forgxyz** [comment]
Closed with PR #24 !
