### ISSUE TITLE
Table: Staking Activities

### ISSUE THREAD

**Issue by 0xissui** [MetricsDAO/near_dbt#64]
## Description

A table tracking staking actions on NEAR

## TODO
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request

**Comment by forgxyz** [comment]
Per roadmap, we can table this for now to focus on higher priorities
(https://docs.google.com/document/d/1XI_IWfuHRvnwI-LA31kLLJbTF-5JM-mt8hYK2I6IqCQ/edit)

**Comment by eevui** [comment]
@forgxyz By staking activities, I assume we include delegations as it looks like nobody has successfully done a "naked" stake on NEAR according to the data we have.

Assuming we include delegations, I can identify the following columns that would be in this table.
- block_timestamp
- tx_hash
- stake_receiver (in case of "naked" stakes: == to stake_signer; in case of delegations: the pool)
- stake_signer
- stake_amount (can be negative to indicate an unstaking)

Should rewards be included as a staking activity?

**Comment by eevui** [comment]
Potentially will have to create a new table to store validated pools (pools created by poolv1.near and others), just so we can filter out "stakes" and "unstakes" on contracts that aren't actually staking into the network.

**Comment by forgxyz** [comment]
Agree, there's no need to combine pseudo-related data into one table. 

The primary table here should be delegations: users committing NEAR to and withdrawing stake from validators.

We can also try to scrape total delegation from [these messages](https://explorer.mainnet.near.org/transactions/8h8A54mJnHs6doVm6hgmbpzZ8KZ5PFNykjesFGKNULAA), as well as something like epoch rewards so end users can easily determine staking rewards being paid out.

ON "validated" pools - we could either include that in the main staking pool next to the validator column, or in a metadata model with some of this additional model. I am leaning towards the latter.

**Comment by eevui** [comment]
> We can also try to scrape total delegation from [these messages](https://explorer.mainnet.near.org/transactions/8h8A54mJnHs6doVm6hgmbpzZ8KZ5PFNykjesFGKNULAA), as well as something like epoch rewards so end users can easily determine staking rewards being paid out.

I don't believe this particular message is staking into the NEAR network, but rather it looks like a contract offered by Stader Labs called [NearX](https://medium.com/staderlabs/nearx-the-next-gen-liquid-staking-solution-on-near-9660943d35d7). While it does indirectly stake into the network, I don't believe this should be part of this staking activities table.

> On "validated" pools - we could either include that in the main staking pool next to the validator column, or in a metadata model with some of this additional model. I am leaning towards the latter.

I'm not entirely sure what you mean here. What do you mean by "main staking pool" a new staking pool table? And what do you mean by a "metadata model with some of this additional model"?

We can easily find which pools are actual staking pools from calls to the [poolv1 account](https://explorer.mainnet.near.org/accounts/poolv1.near) and similar (such as the regular pool.near account and perhaps others that I'm not wary of right now).

Just to confirm, we're including staking rewards here? Though it seems that staking rewards are a bit iffy to gather. Balances are updated by way of other actions, or a ping action, and pulling up balances seems to be by individual action.

**Comment by eevui** [comment]
@forgxyz Can I get confirmation on whether the proposed schema is good?

- block_timestamp
- tx_hash
- stake_receiver (in case of "naked" stakes: == to stake_signer; in case of delegations: the pool)
- stake_signer
- stake_amount (can be negative to indicate an unstaking)

**Comment by eevui** [comment]
It has occurred to me that... you can deposit and stake balance with a pool... but the pool's balance won't be enough to _actually_ start staking with the network. As is here: <https://explorer.near.org/transactions/88hhkChPRsH4XEo6A6tjbpv4gpJQysdFbLVJuyuyovrX>

**Comment by eevui** [comment]
Also, unstakes can take around 2 epochs to complete... how do we account for that?

**Comment by forgxyz** [comment]
Let's include the action where a delegation is unstaked. Is there a second event when the initial stake is received back to the users wallet?

This first staking table should include delegating / undelegating actions. I believe this could include epoch rewards as the stake amount would increase by that reward. 

The goal of the table should be to calculate a wallet's staked balance based on these actions.

**Comment by eevui** [comment]
> Let's include the action where a delegation is unstaked.

Unstaking doesn't immediately return funds back to the user's wallet, there's an intermediate "unstaked balance" in the pool contracts.

> I believe this could include epoch rewards as the stake amount would increase by that reward.

I think this is a bit difficult to find out, so much so, there is a "ping" action to update balances.

These concerns aside, I'd like to propose a staking pools table first. This should cut down on the amount of queries I'm making :joy: Should I create a new issue for this?

**Comment by eevui** [comment]
@forgxyz Here's a sample 100 rows from my current query. This doesn't use my proposed staking table.

[delegations.csv](https://github.com/MetricsDAO/near_dbt/files/9416609/delegations.csv)

Considering that not all "stake" transactions _actually_ stake into the network (i.e. a "stake" transaction can be successful, but not actually stake due to not having enough NEAR to stake), I haven't checked whether all these transactions are actually staking or not.

In general however, it seems possible to calculate how much NEAR an account has delegated with a pool via this query. As long as the pool they are staking in is actively staking. As for rewards, however... that is still left to be answered.

**Comment by eevui** [comment]
Here's an update 100 row result with absolute amounts, adding an action column instead.

[delegations and staking(3).csv](https://github.com/MetricsDAO/near_dbt/files/9575507/delegations.and.staking.3.csv)
