### ISSUE TITLE
Table: USN 

### ISSUE THREAD

**Issue by 0xissui** [MetricsDAO/near_dbt#66]
## Description

A table tracking USN metrics on NEAR

## TODO
- [x]  Design the schema for this table
- [x]  Get confirmation on schema
- [x]  Build schema
- [x]  Schema build review
- [x]  Submit Pull Request

**Comment by forgxyz** [comment]
This table should curate transactions related to USN: mints, burns (does NEAR use that terminology?), transfers, etc.

**Comment by geewynn** [comment]
I will like to propose the following columns for the initial schema:

- actions,
- block_id,
- block_hash,
- tx_hash,
- block_timestamp,
- nonce,
- signature,
- tx_receiver,
- tx_signer,
- old_owner,
- new_owner,
- amount


| BLOCK_TIMESTAMP         | TXN_HASH                                    | LOG_ID                                           | LOGS | AMOUNT_IN                   | AMOUNT_OUT | POOL_ID | TOKEN0      | TOKEN1                                                         |
|-------------------------|---------------------------------------------|--------------------------------------------------|------|-----------------------------|------------|---------|-------------|----------------------------------------------------------------|

**Comment by forgxyz** [comment]
We can limit the extra fields as curated tables should really just have the core details. I'd nix:
- block_hash
- nonce
- signature


I am curious what the total possible `actions` are that you have found.

What are the following addresses? I want to make sure we're as clear as possible with the naming for these
- tx_receiver,
- tx_signer,
- old_owner,
- new_owner,

**Comment by geewynn** [comment]
Possible actions are identified by the method names, the ones i identified are the `ft_transfer_call` and `ft_transfer` and `withdraw`

tx_receiver - the contract address that receives the transaction - this is `USN`
tx_signer - this is the sender of the transaction, it seems to be same as the `old_owner` colums
old_owner - the previous owner of the token, address initiating the transaction.
new_owner - the address that receives the token.

**Comment by forgxyz** [comment]
Gotcha, I see in the transaction information on the block explorer, the message is using `old_owner` and `new_owner` so it makes sense to keep that terminology. Let's just be sure to document that clearly for the users.
