### ISSUE TITLE
Metrics: Active Wallets

### ISSUE THREAD

**Issue by chuxinh** [MetricsDAO/near_dbt#9]
## Description
A table tracking the number of wallets actively making transactions in a given day, week, month

## TODO
- [x]  Design the schema for this table
- [x]  Get confirmation on schema
- [x]  Build schema
- [x]  Schema build review
- [x]  Submit Pull Request

**Comment by 0xissui** [comment]
Proposed Schema
- [ ] Date
- [ ] Period (daily, weekly, monthly)
- [ ] Active Wallet Count
- [ ] Active Wallets Cumulative

**Comment by forgxyz** [comment]
I wouldn't combine time periods into one table, you'll end up with complications in the `date` field.

**Comment by 0xissui** [comment]
Okay, this was the schema I saw in harmony currently for `METRIC_UNIQUE_USERS_COUNT`.
Should we have a table for each period, then?

**Comment by chuxinh** [comment]
what do you think about having just one date filed, but having rolling 7 days, 30 days as metric columns?

**Comment by 0xissui** [comment]
That sounds good! So

- [ ] Date (day)
- [ ] Daily Active Wallets (sum of active wallets for the day)
- [ ] Weekly Active Wallets (sum of active wallets past 7 days)
- [ ] Monthly Active Wallets (sum of active wallets past 30 days)

**Comment by forgxyz** [comment]
I like this approach, feel free to start working it up!
